<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MylogicService_group\home\header\**" />
    <Compile Remove="MylogicService_group\home\leftMenu\**" />
    <Content Remove="MylogicService_group\home\header\**" />
    <Content Remove="MylogicService_group\home\leftMenu\**" />
    <EmbeddedResource Remove="MylogicService_group\home\header\**" />
    <EmbeddedResource Remove="MylogicService_group\home\leftMenu\**" />
    <None Remove="MylogicService_group\home\header\**" />
    <None Remove="MylogicService_group\home\leftMenu\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="MylogicService_group\error\" />
    <Folder Include="MylogicService_group\users\" />
    <Folder Include="MylogicService_group\users\Album\" />
    <Folder Include="MylogicService_group\users\Album\album-upload\" />
    <Folder Include="MylogicService_group\users\Album\show-albums\" />
  </ItemGroup>

</Project>
